#! /bin/sh

# pick a random colorfile on start
# set wallpaper

walls=$HOME/.Xresources.d/walls
dir=$HOME/.Xresources.d/colors
filename=$HOME/.Xresources.d/.colors
curcol=$(awk 'NR==5{gsub(/>/," ");print $2}' $filename | cut -d '/' -f6)

pik() {
	#cd $dir
	#ls|sort -R|tail -1|while read file; do
		#sed -i "s/$curcol/$file/g" $filename
	#done
	#cd $HOME
	xrdb -merge ~/.Xresources
}
setwall() {
    if [[ -z $wallpaper ]]; then
	filename=$(awk 'NR==5{gsub(/</," ");print $2}' $HOME/.Xresources.d/.colors | cut -d '/' -f6 | rev | cut -c 2- | rev)
        wallpaper=$walls/$wallpaper.jpg
    fi

    if [ -f "$wallpaper" ]; then
        cmd="hsetroot -tile $wallpaper"
    else
        cmd="hsetroot -fill $walls/default.jpg"
    fi

    $cmd
}
showme() {
	printcol=$(awk 'NR==5{gsub(/</," ");print $2}' $HOME/.Xresources.d/.colors | cut -d '/' -f6 | rev | cut -c 2- | rev)
	notify-send "palette in use - $printcol"
}

wallpaper=$1
pik
setwall
# showme
