[[ -f ~/.zshrc ]] && . ~/.zshrc

[[ -z $DISPLAY && XDG_VTNR -eq 1 ]] &&
export PATH=$PATH:$HOME/bin:$HOME/work/scripts:$HOME/.Xresources.d:$HOME/go/bin:/home/samreen/.local/bin &&
export EDITOR='emacsclient -nc' &&
export VISUAL='emacsclient -nc' &&
export VISUAL=emacsclient &&
export bti=~/work/git/bti-nextgen &&
export stuff=~/work/git/stuff &&
source ~/bin/set_tokens &&
exec startx
