[[ -f ~/.zshrc ]] && . ~/.zshrc

[[ -z $DISPLAY && XDG_VTNR -eq 1 ]] &&
export PATH=$PATH:$HOME/bin:$HOME/Work/Scripts:$HOME/.Xresources.d:$HOME/go/bin &&
export EDITOR='emacsclient -nc' &&
export VISUAL='emacsclient -nc' &&
export VISUAL=emacsclient &&
export bti=~/Work/Git/bti-nextgen &&
export bti2=~/Work/Git/bti/bti-nextgen &&
export fusion=~/Work/Git/fusion &&
source ~/bin/set_tokens &&
exec startx
